import type { Player, DpsRecord } from "./db"

// Dados de exemplo para jogadores
export const samplePlayers: Player[] = [
  {
    playerBaseId: 1001,
    name: "Guerreiro1",
    guild: "INFERNUS",
    class: "Tank",
    avgDps: "1200",
    maxDps: "1800",
    avgRating: "8.5",
    isHealer: false,
  },
  {
    playerBaseId: 1002,
    name: "Curandeiro1",
    guild: "INFERNUS",
    class: "Quedasanta",
    avgDps: "800",
    maxDps: "1200",
    avgRating: "9.0",
    isHealer: true,
  },
  {
    playerBaseId: 1003,
    name: "Mago1",
    guild: "INFERNUS",
    class: "Frost",
    avgDps: "1500",
    maxDps: "2200",
    avgRating: "8.7",
    isHealer: false,
  },
  {
    playerBaseId: 1004,
    name: "Assassino1",
    guild: "INFERNUS",
    class: "Adagas",
    avgDps: "1800",
    maxDps: "2500",
    avgRating: "9.2",
    isHealer: false,
  },
  {
    playerBaseId: 1005,
    name: "Suporte1",
    guild: "INFERNUS",
    class: "Endemoniado",
    avgDps: "1100",
    maxDps: "1600",
    avgRating: "8.0",
    isHealer: false,
  },
]

// Dados de exemplo para registros de DPS
export const sampleDpsRecords: DpsRecord[] = [
  {
    playerId: 1,
    playerBaseId: 1001,
    playerName: "Guerreiro1",
    playerClass: "Tank",
    dps: 1200,
    rating: 8.5,
    date: "2023-03-01",
    huntType: "Dungeon",
    isHeal: false,
  },
  {
    playerId: 1,
    playerBaseId: 1001,
    playerName: "Guerreiro1",
    playerClass: "Tank",
    dps: 1800,
    rating: 9.0,
    date: "2023-03-02",
    huntType: "Raid",
    isHeal: false,
  },
  {
    playerId: 2,
    playerBaseId: 1002,
    playerName: "Curandeiro1",
    playerClass: "Quedasanta",
    dps: 800,
    rating: 9.0,
    date: "2023-03-01",
    huntType: "Dungeon",
    isHeal: true,
  },
  {
    playerId: 2,
    playerBaseId: 1002,
    playerName: "Curandeiro1",
    playerClass: "Quedasanta",
    dps: 1200,
    rating: 9.5,
    date: "2023-03-02",
    huntType: "Raid",
    isHeal: true,
  },
  {
    playerId: 3,
    playerBaseId: 1003,
    playerName: "Mago1",
    playerClass: "Frost",
    dps: 1500,
    rating: 8.7,
    date: "2023-03-01",
    huntType: "Dungeon",
    isHeal: false,
  },
  {
    playerId: 3,
    playerBaseId: 1003,
    playerName: "Mago1",
    playerClass: "Frost",
    dps: 2200,
    rating: 9.2,
    date: "2023-03-02",
    huntType: "Raid",
    isHeal: false,
  },
  {
    playerId: 4,
    playerBaseId: 1004,
    playerName: "Assassino1",
    playerClass: "Adagas",
    dps: 1800,
    rating: 9.2,
    date: "2023-03-01",
    huntType: "Dungeon",
    isHeal: false,
  },
  {
    playerId: 4,
    playerBaseId: 1004,
    playerName: "Assassino1",
    playerClass: "Adagas",
    dps: 2500,
    rating: 9.5,
    date: "2023-03-02",
    huntType: "Raid",
    isHeal: false,
  },
  {
    playerId: 5,
    playerBaseId: 1005,
    playerName: "Suporte1",
    playerClass: "Endemoniado",
    dps: 1100,
    rating: 8.0,
    date: "2023-03-01",
    huntType: "Dungeon",
    isHeal: false,
  },
  {
    playerId: 5,
    playerBaseId: 1005,
    playerName: "Suporte1",
    playerClass: "Endemoniado",
    dps: 1600,
    rating: 8.5,
    date: "2023-03-02",
    huntType: "Raid",
    isHeal: false,
  },
]

